---
title: ""
format:
  html:
    title-block: false
toc: true
toc-depth: 3
filters:
  - filters/bibsections.lua
---

## Overview

My research interests include cryptography and its applications to secure biometrics, data-centric security, and network security. Since joining the French Air and Space Force Academy, I have also developed an interest in communication infrastructures in the aerospace domain, especially for service continuity, distributed computing in space environments, and security issues related to applications of defense interest.


## Publications

### Journal articles

::: {.bibsection file="references/journals.bib" csl="styles/ieee.csl"}
:::

### Conference papers

::: {.bibsection file="references/conferences.bib" csl="styles/ieee.csl"}
:::

### Magazine articles

::: {.bibsection file="references/magazines.bib" csl="styles/ieee.csl"}
:::


## Doctoral supervision

### Ongoing supervision

- Mehdi Chourib (since September 2024) - Network Covert Channels
- Baptiste Bazin (since October 2025) - Access Control Encryption
- Dorine Chagnon (2022-2025) - Network Path Validation

### Past supervision


- Axel Durbet (2021-2024) - Privacy-preserving Biometric Authentication ([ANR PRIVABIO](https://privabio.limos.fr/))